name: Cordova Integration Tests
on:
  push:
  pull_request:

jobs:
  test-cordova:
    name: Cordova Native Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up workspace
        uses: ./.github/actions/setup
        with:
          node-version: 23

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platform tools
        run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Build Cordova app
        working-directory: test-cordova
        run: npx cordova build android

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            # Install the Cordova app APK.
            adb install test-cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk

            # Run the Playwright tests.
            cd test-cordova && npx playwright test
